demo/urls.py
from django.conf.urls import url

from . import views

app_name = 'demo'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^count_list/$', views.CountListView.as_view(), name='count_list'),
    url(r'^count_list/add$', views.add, name='add'),
    url(r'^email$', views.EmailView.as_view(), name='email'),
    url(r'^email/send$', views.send_email, name='send_email'),
]

demo2/urls.py
from django.conf.urls import url
from . import views

app_name = 'demo2'

urlpatterns = [
    # ex: /demo2/
    # url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^$', views.index, name='index'),
    url(r'^reactjs/$', views.reactjs, name='reactjs'),
    url(r'^funds/$', views.funds, name='funds'),
    url(r'^download_html/$', views.download_html, name='download_html'),
    url(r'^analyze_page/$', views.analyze_page, name='analyze_page'),
    # ex: /demo2/5/
    url(r'^(?P<fund_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /demo2/5/results/
    url(r'^(?P<fund_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /demo2/5/vote/
    url(r'^(?P<fund_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

django_demo/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^demo/', include('demo.urls')),
    url(r'^demo2/', include('demo2.urls')),
]

demo/models.py
from django.db import models

# Create your models here.

class Counter(models.Model):
    text = models.CharField(max_length=200)
    count = models.IntegerField(default=0)

    def __str__(self):
        return self.text

demo2/models.py
from django.db import models

# Create your models here.

class FundInfo(models.Model):
    id = models.AutoField(primary_key=True)
    fid = models.CharField(max_length=64)
    symbol = models.CharField(max_length=64)
    name = models.CharField(max_length=64)
    wave3 = models.FloatField(null=True)
    wave_evaluate3 = models.CharField(max_length=32, null=True)
    risk3 = models.FloatField(null=True)
    risk_evaluate3 = models.CharField(max_length=32, null=True)
    sharp3 = models.FloatField(null=True)
    sharp_evaluate3 = models.CharField(max_length=32, null=True)
    return_rate = models.FloatField(null=True) # return
    rank = models.IntegerField(null=True)
    update_time = models.DateTimeField(null=True)

    def __str__(self):
        return self.name


class PageContent(models.Model):
    id = models.AutoField(primary_key=True)
    url = models.CharField(max_length=512)
    content = models.TextField()
    update_time = models.DateTimeField(null=True)

    def __str__(self):
        return self.url

demo/views.py
from django.core.mail import send_mail
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse


import logging

# Create your views here.
from django.views import generic
from .models import Counter

logger = logging.getLogger(__name__)

class IndexView(generic.TemplateView):
    template_name = "demo/index.html"

    def get(self, request, *args, **kwargs):
        logger.info("IndexView")
        return super().get(request, *args, **kwargs)


class CountListView(generic.ListView):
    template_name = "demo/count_list.html"
    context_object_name = 'count_list'
    logger.info("CountListView_init")

    def get_queryset(self):
        return Counter.objects.all()


def add(request):
    t = request.POST['name']
    try:
        c = Counter.objects.get(text=t)
    except Counter.DoesNotExist:
        logger.info("add %s" % t)
        c = Counter(text=t, count=0)
        c.save()
    else:
        c.count += 1
        c.save()
    return HttpResponseRedirect(reverse('demo:count_list'))


class EmailView(generic.TemplateView):
    template_name = "demo/email.html"
    logger.info("Email_init")


def send_email(request):
    text = request.POST['content']
    logger.info("send_email: text<%s>" % text)
    send_mail('Subject here',
              text,
              '284416589@qq.com',
              ['284416589@qq.com'],
              fail_silently=False)
    return HttpResponseRedirect(reverse('demo:email'))

demo2/views.py
import logging

# Create your views here.
from django.http import HttpResponse
from django.views import generic
from django.template import loader

from demo2.models import FundInfo, PageContent
from .spider import util, mstar_fund
from django.utils import timezone

logger = logging.getLogger(__name__)

class IndexView(generic.TemplateView):
    template_name = "demo2/index.html"

    def get(self, request, *args, **kwargs):
        logger.info("IndexView")
        return super().get(request, *args, **kwargs)

def index(request):
    latest_page_list = PageContent.objects.order_by('-update_time')[:5]
    template = loader.get_template('demo2/index.html')  # 获取模版
    context = {
        'latest_page_list': latest_page_list,   # 模版参数赋值
    }
    return HttpResponse(template.render(context, request))  # 渲染


def reactjs(request):
    template = loader.get_template('demo2/reactjs.html')  # 获取模版
    return HttpResponse(template.render(request=request))  # 渲染


def funds(request):
    latest_fundinfo_list = FundInfo.objects.order_by('-update_time')[:5]
    template = loader.get_template('demo2/funds.html')  # 获取模版
    context = {
        'latest_fundinfo_list': latest_fundinfo_list,   # 模版参数赋值
    }
    return HttpResponse(template.render(context, request))  # 渲染

def detail(request, fund_id):
    return HttpResponse("You're looking at fund %s." % fund_id)

def results(request, fund_id):
    response = "You're looking at the results of fund %s."
    return HttpResponse(response % fund_id)

def vote(request, fund_id):
    return HttpResponse("You're voting on fund %s." % fund_id)

def download_html(request):
    url_str = request.POST['url']
    html = util.getHtml(url_str)

    old_pc = None
    try:
        old_pc = PageContent.objects.get(url=url_str)
    except PageContent.DoesNotExist:
        pass

    if old_pc != None:
        old_pc.content = html
        old_pc.update_time = timezone.now()
        old_pc.save()
    else:
        pc = PageContent(url=url_str, content=html, update_time=timezone.now())
        pc.save()

    return HttpResponse("download_html %s\n%s" % (url_str, html))


def analyze_page(request):
    pageid = request.POST['pageid']

    try:
        pc = PageContent.objects.get(id=pageid)
        mstar_fund.analyContent(pc.content)
        return HttpResponse("analyze done.")
    except PageContent.DoesNotExist:
        return HttpResponse("page not fund. pageid<%s>" % pageid)

demo/templates/demo/count_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<a href="{% url 'demo:index' %}" >index</a>
<br>

{{ count_list }}

<table>
    <tbody>
    {% for c in count_list %}
    <tr>
        <td>{{ c.text }}</td>
        <td>{{ c.count }}</td>
        <td>TODO: 此处应有count++按钮</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<br>
<p>Add Counter</p>
<form action="{% url 'demo:add' %}" method="post">
    {% csrf_token %}
    Counter name:<br>
    <input type="text" name="name">
    <br>
    <input type="submit" value="Submit">
</form>

</body>
</html>

demo/templates/demo/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Email</title>
</head>
<body>
<a href="{% url 'demo:index' %}" >index</a>
<br>

<form action="{% url 'demo:send_email' %}" method="post">
    {% csrf_token %}
    Email Address:
    <input type="text" name="address" value="284416589@qq.com"/>
    <br>
    Content:
    <input type="text" name="content"/>
    <br>
    <input type="submit" value="Send"/>
</form>

</body>
</html>

demo/templates/demo/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<ul>
    <li>
        <a href="{% url 'demo:count_list' %}">count_list.html</a>
    </li>
    <li>
        <a href="{% url 'demo:email' %}">email.html</a>
    </li>

</ul>


</body>
</html>

demo2/templates/demo2/funds.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Funds</title>
</head>
<body>

{% if latest_fundinfo_list %}
    <ul>
    {% for fund in latest_fundinfo_list %}
        <li><a href="/demo2/{{ fund.id }}/">{{ fund.symbol }} {{ fund.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No FUNDs are available.</p>
{% endif %}

</body>
</html>

demo2/templates/demo2/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Demo2</title>
</head>
<body>

<h1>Demo 2 .</h1>



<h2>页面列表</h2>

<ul>
    <li>
        <a href="{% url 'demo2:funds' %}">funds.html</a>
    </li>
    <li>
        <a href="{% url 'demo2:reactjs' %}">reactjs.html</a>
    </li>
</ul>


{#<h2>{{ question.question_text }}</h2>#}
<h2>抓取网址</h2>

{#{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}#}

<form action="{% url 'demo2:download_html' %}" method="post">
{#Cross Site Request Forgeries#}
{% csrf_token %}
    <input type="text" name="url" value="https://cn.morningstar.com/fundcompany/default.aspx"/>
<input type="submit" value="抓页面" />
</form>


<h2>分析页面</h2>

{% if latest_page_list %}
    <ul>
        {% for page in latest_page_list %}
            <li>{{ page.id }} {{ page.url }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No Pages are available.</p>
{% endif %}


<form action="{% url 'demo2:analyze_page' %}" method="post">
    {#Cross Site Request Forgeries#}
    {% csrf_token %}
    <input type="text" name="pageid" />
{#    分析程序选择#}
    {#{% for choice in question.choice_set.all %}#}
    {#    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />#}
    {#    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />#}
    {#{% endfor %}#}
    <input type="submit" value="分析页面" />
</form>

</body>
</html>

demo2/templates/demo2/reactjs.html
{% load render_bundle from webpack_loader %}
{#{% load staticfiles %}#}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ReactJs Demo</title>
{#    <script src="{% static "js/jquery-3.2.1.min.js" %}" type="text/javascript"></script>#}
</head>
<body>

<div id="menu"></div>
<div id="react-app"></div>
{%  render_bundle 'main' %}

</body>

</html>